#!/bin/sh -e
# TODO: Lintian says that gconf-schemas or update-gconf-defaults
# should be used in stead of gconftool-2 should 
schemadir=/etc/gconf/schemas
schema_DATA=maemosec_certman.schemas
GCONFTOOL=gconftool-2
GCONF_SCHEMA_CONFIG_SOURCE=xml::/etc/gconf/gconf.xml.defaults

if [ "$1" = "configure" ]; then
	GCONF_CONFIG_SOURCE=${GCONF_SCHEMA_CONFIG_SOURCE} ${GCONFTOOL} \
	--makefile-install-rule ${schemadir}/${schema_DATA}
fi

